name: ci
permissions: {}
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-tools:
    runs-on: ubuntu-latest
    name: Build Go Tools
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: scripts/go.mod
          cache-dependency-path: scripts/go.sum
      - name: Build Go tools
        run: make build-tools
      - name: Upload built tools
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: go-tools
          path: tmp/bin/
          retention-days: 1
          if-no-files-found: error

  matrix:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    needs: build-tools
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint Alerts
            run: make alerts-lint
          - name: Generate YAML
            run: make generate && git diff --exit-code
          - name: Lint Grafana Dashboards
            run: make dashboards-lint
          - name: Format JSONNET
            run: make jsonnet-fmt && git diff --exit-code
          - name: Lint JSONNET
            run: make jsonnet-lint
          - name: Format MD
            run: make markdownfmt && git diff --exit-code
          - name: Lint MD
            run: make vale && git diff --exit-code
          - name: Lint YAML
            run: make pint-lint
          - name: Run unit tests
            run: make test

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download built tools
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: go-tools
          path: tmp/bin/
      - name: Make tools executable and update timestamps
        run: |
          chmod +x tmp/bin/*
          touch tmp/bin/*
      - run: ${{ matrix.run }}
